In [2]:
import pandas as pd # import pandas module

# create list of lits
exp_listOflist = [
    [2,4],
    [4,2]
]

# initialize the DataFrame
gene_frame = pd.DataFrame(exp_listOflist, 
                          columns = ["treatmentA","treatmentB"],
                          index = ["Billy","Bob"]) # row names



gene_frame

       treatmentA  treatmentB
Billy           2           4
Bob             4           2

In [3]:
import pandas as pd # import pandas module

# create list of dictionaries
exp_listOfDict = [
    {"treatmentA":2,"treatmentB":4},
    {"treatmentA":4,"treatmentB":2}
]

# initialize the DataFrame
gene_frame = pd.DataFrame(exp_listOfDict, 
                          index=["Billy","Bob"]) # row names



gene_frame

       treatmentA  treatmentB
Billy           2           4
Bob             4           2

In [4]:
import pandas as pd # import pandas module

# create dictionary of lists
exp_dictOfList = {
    "treatmentA":[2,4],
    "treatmentB":[4,2]
}

# initialize the DataFrame
gene_frame = pd.DataFrame(exp_dictOfList, 
                          index=["Billy","Bob"]) # row names

gene_frame

       treatmentA  treatmentB
Billy           2           4
Bob             4           2

In [6]:
import pandas as pd # import pandas module

# create dictionary of dictionary
exp_dictOfDict = {
    "treatmentA":{"Billy":2, "Bob":4},
    "treatmentB":{"Billy":4, "Bob":2}
}

# initialize the DataFrame
gene_frame = pd.DataFrame(exp_dictOfDict) # row names

gene_frame

       treatmentA  treatmentB
Billy           2           4
Bob             4           2

In [8]:
import pandas as pd # import pandas module

# create dictionary of dictionary
exp_dictOfDict = {
    "treatmentA":{"Billy":2, "Bob":4},
    "treatmentB":{"Billy":4, "Bob":2}
}

gene_frame = pd.DataFrame.from_dict(exp_dictOfDict, 
                                    orient='index')

gene_frame

            Billy  Bob
treatmentA      2    4
treatmentB      4    2

In [4]:
import pandas as pd # import pandas module
import numpy as np # import numpy module
                   # this module can classify
                    # python objects that make
                    # math easier later...

In [11]:
column_names = [
    "peak_chr",   # chromosome where peak is at
    "peak_start", # peak start site
    "peak_stop",  # peak stop site
    "peak_name", # name of peak
    "peak_signal", # signal score of peak
    "peak_strand", # strand where peak is found 
                   #(its always strandless)
    "gene_chr", # chromosome where gene is at
    "gene_start", # gene start site
    "gene_stop", # gene stop site
    "gene_name", # name of gene
    "gene_signal", # gene signal score
    "gene_strand", # strand where gene is found
    "distance" # distance from peak to gene
]

In [12]:
column_types = {"peak_chr" : str,
                "peak_start" : np.int64,
                "peak_stop" : np.int64,
                "peak_name" : str,
                "peak_signal" : np.float64,
                "peak_strand":str,
                "gene_chr" : str,
                "gene_start" : np.int64,
                "gene_stop" : np.int64,
                "gene_name" : str, 
                "gene_signal" : np.float64,
                "gene_strand" : str,
                "distance" : np.float64}

In [15]:
closest_df = pd.read_table("bedtools_closest.txt",
              sep="\t",
             header=None,
             names= column_names,
             dtype=column_types)
closest_df.head(n=3) # This show the top 3 lines of the dataframe

,peak_chr,peak_start,peak_stop,peak_name,peak_signal,peak_strand,gene_chr,gene_start,gene_stop,gene_name,gene_signal,gene_strand,distance
0,Chr1,99170,99671,chipSampleRepAll_peak_4,449.0,.,Chr1,97411,99240,AT1G01230,0.0,+,0.0
1,Chr1,171294,171795,chipSampleRepAll_peak_6,171.0,.,Chr1,168558,171386,AT1G01460,0.0,+,0.0
2,Chr1,171294,171795,chipSampleRepAll_peak_6,171.0,.,Chr1,171524,172948,AT1G01470,0.0,-,0.0
3,Chr1,190092,190593,chipSampleRepAll_peak_8,436.0,.,Chr1,187144,190472,AT1G01510,0.0,+,0.0
4,Chr1,190092,190593,chipSampleRepAll_peak_8,436.0,.,Chr1,190407,192436,AT1G01520,0.0,+,0.0

In [28]:
closest_df.columns # get column information

Index([u'peak_chr', u'peak_start', u'peak_stop', u'peak_name', u'peak_signal',
       u'peak_strand', u'gene_chr', u'gene_start', u'gene_stop', u'gene_name',
       u'gene_signal', u'gene_strand', u'distance'],
      dtype='object')

In [29]:
closest_df.index # get index information

RangeIndex(start=0, stop=1398, step=1)

In [31]:
closest_df.dtypes # get data types of each column

peak_chr        object
peak_start       int64
peak_stop        int64
peak_name       object
peak_signal    float64
peak_strand     object
gene_chr        object
gene_start       int64
gene_stop        int64
gene_name       object
gene_signal    float64
gene_strand     object
distance       float64
dtype: object

In [32]:
closest_df.shape # get dataFrame dimensions

(1398, 13)

In [33]:
closest_df.iloc[1,:]

peak_chr                          Chr1
peak_start                      171294
peak_stop                       171795
peak_name      chipSampleRepAll_peak_6
peak_signal                        171
peak_strand                          .
gene_chr                          Chr1
gene_start                      168558
gene_stop                       171386
gene_name                    AT1G01460
gene_signal                          0
gene_strand                          +
distance                             0
Name: 1, dtype: object

In [52]:
closest_df.iloc[range(1,3),:]

,peak_chr,peak_start,peak_stop,peak_name,peak_signal,peak_strand,gene_chr,gene_start,gene_stop,gene_name,gene_signal,gene_strand,distance
1,Chr1,171294,171795,chipSampleRepAll_peak_6,171.0,.,Chr1,168558,171386,AT1G01460,0.0,+,0.0
2,Chr1,171294,171795,chipSampleRepAll_peak_6,171.0,.,Chr1,171524,172948,AT1G01470,0.0,-,0.0

In [53]:
closest_df.loc[range(1,3),:]

,peak_chr,peak_start,peak_stop,peak_name,peak_signal,peak_strand,gene_chr,gene_start,gene_stop,gene_name,gene_signal,gene_strand,distance
1,Chr1,171294,171795,chipSampleRepAll_peak_6,171.0,.,Chr1,168558,171386,AT1G01460,0.0,+,0.0
2,Chr1,171294,171795,chipSampleRepAll_peak_6,171.0,.,Chr1,171524,172948,AT1G01470,0.0,-,0.0

In [8]:
closest_sorted_df = closest_df.sort_index(ascending=False)
closest_sorted_df.head(n=3)

,peak_chr,peak_start,peak_stop,peak_name,peak_signal,peak_strand,gene_chr,gene_start,gene_stop,gene_name,gene_signal,gene_strand,distance
1397,Chr5,26923340,26923841,chipSampleRepAll_peak_1824,105.0,.,Chr5,26921583,26923488,AT5G67460,0.0,-,0.0
1396,Chr5,26920686,26921187,chipSampleRepAll_peak_1823,628.0,.,Chr5,26921583,26923488,AT5G67460,0.0,-,397.0
1395,Chr5,26910421,26910922,chipSampleRepAll_peak_1822,156.0,.,Chr5,26910204,26912103,AT5G67430,0.0,+,0.0

In [54]:
closest_sorted_df.iloc[range(1,3),:]

,peak_chr,peak_start,peak_stop,peak_name,peak_signal,peak_strand,gene_chr,gene_start,gene_stop,gene_name,gene_signal,gene_strand,distance
1396,Chr5,26920686,26921187,chipSampleRepAll_peak_1823,628.0,.,Chr5,26921583,26923488,AT5G67460,0.0,-,397.0
1395,Chr5,26910421,26910922,chipSampleRepAll_peak_1822,156.0,.,Chr5,26910204,26912103,AT5G67430,0.0,+,0.0

In [57]:
closest_sorted_df.loc[range(1,3),:]

,peak_chr,peak_start,peak_stop,peak_name,peak_signal,peak_strand,gene_chr,gene_start,gene_stop,gene_name,gene_signal,gene_strand,distance
1,Chr1,171294,171795,chipSampleRepAll_peak_6,171.0,.,Chr1,168558,171386,AT1G01460,0.0,+,0.0
2,Chr1,171294,171795,chipSampleRepAll_peak_6,171.0,.,Chr1,171524,172948,AT1G01470,0.0,-,0.0

In [58]:
closest_sorted_df.loc[closest_sorted_df.index>1394,:]

,peak_chr,peak_start,peak_stop,peak_name,peak_signal,peak_strand,gene_chr,gene_start,gene_stop,gene_name,gene_signal,gene_strand,distance
1397,Chr5,26923340,26923841,chipSampleRepAll_peak_1824,105.0,.,Chr5,26921583,26923488,AT5G67460,0.0,-,0.0
1396,Chr5,26920686,26921187,chipSampleRepAll_peak_1823,628.0,.,Chr5,26921583,26923488,AT5G67460,0.0,-,397.0
1395,Chr5,26910421,26910922,chipSampleRepAll_peak_1822,156.0,.,Chr5,26910204,26912103,AT5G67430,0.0,+,0.0

In [61]:
closest_sorted_df.iloc[1,4]

628.0

In [63]:
closest_sorted_df.loc[1,"gene_name"]

'AT1G01460'

In [65]:
closest_sorted_df.loc[1,4]

TypeError: cannot do label indexing on <class 'pandas.core.indexes.base.Index'> with these indexers [4] of <type 'int'>

In [66]:
closest_sorted_df.loc[0:3,"gene_name"]

Series([], Name: gene_name, dtype: object)

In [9]:
# series of gene names from rows with values 0-2
some_genes = closest_sorted_df.loc[range(0,3),"gene_name"]
print some_genes

0    AT1G01230
1    AT1G01460
2    AT1G01470
Name: gene_name, dtype: object

In [17]:
# check if "AT1G01230" is a value in the series
print "AT1G01230" in some_genes.values

True

In [18]:
# check if "AT1G01250" is a value in the series
print "AT1G01250" in some_genes.values

False

In [76]:
closest_sorted_df.loc[0,:]

peak_chr                          Chr1
peak_start                       99170
peak_stop                        99671
peak_name      chipSampleRepAll_peak_4
peak_signal                        449
peak_strand                          .
gene_chr                          Chr1
gene_start                       97411
gene_stop                        99240
gene_name                    AT1G01230
gene_signal                          0
gene_strand                          +
distance                             0
Name: 0, dtype: object

In [77]:
closest_sorted_df.head()

,peak_chr,peak_start,peak_stop,peak_name,peak_signal,peak_strand,gene_chr,gene_start,gene_stop,gene_name,gene_signal,gene_strand,distance
1397,Chr5,26923340,26923841,chipSampleRepAll_peak_1824,105.0,.,Chr5,26921583,26923488,AT5G67460,0.0,-,0.0
1396,Chr5,26920686,26921187,chipSampleRepAll_peak_1823,628.0,.,Chr5,26921583,26923488,AT5G67460,0.0,-,397.0
1395,Chr5,26910421,26910922,chipSampleRepAll_peak_1822,156.0,.,Chr5,26910204,26912103,AT5G67430,0.0,+,0.0
1394,Chr5,26908678,26909179,chipSampleRepAll_peak_1821,303.0,.,Chr5,26910204,26912103,AT5G67430,0.0,+,-1026.0
1393,Chr5,26879377,26879878,chipSampleRepAll_peak_1820,1771.0,.,Chr5,26877271,26879639,AT5G67370,0.0,-,0.0

In [78]:
# rows where peaks overlap genes
closest_df.loc[closest_df.loc[:,"distance"]==0,:]

,peak_chr,peak_start,peak_stop,peak_name,peak_signal,peak_strand,gene_chr,gene_start,gene_stop,gene_name,gene_signal,gene_strand,distance
0,Chr1,99170,99671,chipSampleRepAll_peak_4,449.0,.,Chr1,97411,99240,AT1G01230,0.0,+,0.0
1,Chr1,171294,171795,chipSampleRepAll_peak_6,171.0,.,Chr1,168558,171386,AT1G01460,0.0,+,0.0
2,Chr1,171294,171795,chipSampleRepAll_peak_6,171.0,.,Chr1,171524,172948,AT1G01470,0.0,-,0.0
3,Chr1,190092,190593,chipSampleRepAll_peak_8,436.0,.,Chr1,187144,190472,AT1G01510,0.0,+,0.0
4,Chr1,190092,190593,chipSampleRepAll_peak_8,436.0,.,Chr1,190407,192436,AT1G01520,0.0,+,0.0
5,Chr1,207626,208127,chipSampleRepAll_peak_10,119.0,.,Chr1,204934,207642,AT1G01570,0.0,+,0.0
6,Chr1,220012,220513,chipSampleRepAll_peak_11,101.0,.,Chr1,218833,221286,AT1G01600,0.0,+,0.0
7,Chr1,268041,268542,chipSampleRepAll_peak_13,268.0,.,Chr1,267992,269819,AT1G01720,0.0,+,0.0
9,Chr1,356675,357176,chipSampleRepAll_peak_15,240.0,.,Chr1,355123,357258,AT1G02030,0.0,-,0.0
12,Chr1,567147,567648,chipSampleRepAll_peak_18,352.0,.,Chr1,564017,567771,AT1G02640,0.0,+,0.0
14,Chr1,587999,588500,chipSampleRepAll_peak_20,186.0,.,Chr1,588002,589480,AT1G02700,0.0,+,0.0
15,Chr1,621160,621661,chipSampleRepAll_peak_21,146.0,.,Chr1,620677,621329,AT1G02813,0.0,+,0.0
16,Chr1,621160,621661,chipSampleRepAll_peak_21,146.0,.,Chr1,621452,623054,AT1G02816,0.0,+,0.0
17,Chr1,707164,707665,chipSampleRepAll_peak_22,156.0,.,Chr1,707484,710041,AT1G03050,0.0,+,0.0
18,Chr1,729626,730127,chipSampleRepAll_peak_23,141.0,.,Chr1,729829,731565,AT1G03070,0.0,+,0.0
19,Chr1,867569,868070,chipSampleRepAll_peak_24,274.0,.,Chr1,865894,867733,AT1G03470,0.0,-,0.0
20,Chr1,898565,899066,chipSampleRepAll_peak_25,262.0,.,Chr1,898479,899794,AT1G03600,0.0,+,0.0
21,Chr1,993048,993549,chipSampleRepAll_peak_27,186.0,.,Chr1,991105,993126,AT1G03900,0.0,+,0.0
22,Chr1,993048,993549,chipSampleRepAll_peak_27,186.0,.,Chr1,993399,995989,AT1G03905,0.0,+,0.0
23,Chr1,1028149,1028650,chipSampleRepAll_peak_28,132.0,.,Chr1,1027852,1029119,AT1G04000,0.0,-,0.0
27,Chr1,1224405,1224906,chipSampleRepAll_peak_33,128.0,.,Chr1,1221410,1224539,AT1G04500,0.0,-,0.0
33,Chr1,2047493,2047994,chipSampleRepAll_peak_45,490.0,.,Chr1,2040409,2047655,AT1G06670,0.0,+,0.0
34,Chr1,2047493,2047994,chipSampleRepAll_peak_45,490.0,.,Chr1,2047633,2049439,AT1G06680,0.0,+,0.0
35,Chr1,2169674,2170175,chipSampleRepAll_peak_47,101.0,.,Chr1,2168560,2169957,AT1G07070,0.0,+,0.0
36,Chr1,2169674,2170175,chipSampleRepAll_peak_47,101.0,.,Chr1,2169976,2172194,AT1G07080,0.0,+,0.0
38,Chr1,2291138,2291639,chipSampleRepAll_peak_49,223.0,.,Chr1,2291368,2294558,AT1G07470,0.0,+,0.0
39,Chr1,2299306,2299807,chipSampleRepAll_peak_50,1197.0,.,Chr1,2296022,2299544,AT1G07480,0.0,-,0.0
40,Chr1,2304920,2305421,chipSampleRepAll_peak_51,282.0,.,Chr1,2304434,2312399,AT1G07510,0.0,+,0.0
41,Chr1,2304920,2305421,chipSampleRepAll_peak_51,282.0,.,Chr1,2304765,2305031,AT1G07500,0.0,-,0.0
43,Chr1,2431972,2432473,chipSampleRepAll_peak_53a,576.0,.,Chr1,2428772,2432091,AT1G07870,0.0,-,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1356,Chr5,25323953,25324454,chipSampleRepAll_peak_1772,445.0,.,Chr5,25322974,25324739,AT5G63130,0.0,+,0.0
1358,Chr5,25383311,25383812,chipSampleRepAll_peak_1775,882.0,.,Chr5,25383809,25387270,AT5G63370,0.0,-,0.0
1359,Chr5,25477207,25477708,chipSampleRepAll_peak_1777,291.0,.,Chr5,25477540,25481715,AT5G63640,0.0,+,0.0
1360,Chr5,25527872,25528373,chipSampleRepAll_peak_1778,490.0,.,Chr5,25526508,25528281,AT5G63790,0.0,-,0.0
1361,Chr5,25676581,25677082,chipSampleRepAll_peak_1779,212.0,.,Chr5,25672465,25676823,AT5G64170,0.0,-,0.0
1362,Chr5,25676581,25677082,chipSampleRepAll_peak_1779,212.0,.,Chr5,25677071,25678702,AT5G64180,0.0,+,0.0
1363,Chr5,25685566,25686067,chipSampleRepAll_peak_1780,518.0,.,Chr5,25683769,25685731,AT5G64210,0.0,-,0.0
1364,Chr5,25703575,25704076,chipSampleRepAll_peak_1781,763.0,.,Chr5,25703648,25705339,AT5G64260,0.0,+,0.0
1365,Chr5,25901858,25902359,chipSampleRepAll_peak_1784,212.0,.,Chr5,25900411,25902127,AT5G64780,0.0,-,0.0
1366,Chr5,25920231,25920732,chipSampleRepAll_peak_1785,442.0,.,Chr5,25916721,25920254,AT5G64840,0.0,-,0.0
1367,Chr5,25948636,25949137,chipSampleRepAll_peak_1786,191.0,.,Chr5,25948953,25953823,AT5G64940,0.0,+,0.0
1369,Chr5,26095581,26096082,chipSampleRepAll_peak_1789,161.0,.,Chr5,26095142,26096114,AT5G65300,0.0,-,0.0
1371,Chr5,26345863,26346364,chipSampleRepAll_peak_1793,100.0,.,Chr5,26343727,26346123,AT5G65840,0.0,-,0.0
1372,Chr5,26345863,26346364,chipSampleRepAll_peak_1793,100.0,.,Chr5,26346265,26347610,AT5G65850,0.0,+,0.0
1374,Chr5,26356313,26356814,chipSampleRepAll_peak_1795,274.0,.,Chr5,26354852,26357905,AT5G65890,0.0,+,0.0
1375,Chr5,26456186,26456687,chipSampleRepAll_peak_1797,171.0,.,Chr5,26456141,26459654,AT5G66210,0.0,-,0.0
1377,Chr5,26541041,26541542,chipSampleRepAll_peak_1799,114.0,.,Chr5,26538394,26541692,AT5G66460,0.0,-,0.0
1378,Chr5,26568338,26568839,chipSampleRepAll_peak_1800,274.0,.,Chr5,26568571,26570461,AT5G66570,0.0,+,0.0
1379,Chr5,26572124,26572625,chipSampleRepAll_peak_1801,265.0,.,Chr5,26572264,26573426,AT5G66580,0.0,+,0.0
1380,Chr5,26588056,26588557,chipSampleRepAll_peak_1802,675.0,.,Chr5,26588410,26592330,AT5G66620,0.0,+,0.0
1381,Chr5,26604742,26605243,chipSampleRepAll_peak_1803,569.0,.,Chr5,26603002,26607012,AT5G66650,0.0,-,0.0
1384,Chr5,26663173,26663674,chipSampleRepAll_peak_1807,456.0,.,Chr5,26663499,26664436,AT5G66780,0.0,+,0.0
1385,Chr5,26672666,26673167,chipSampleRepAll_peak_1809,257.0,.,Chr5,26672872,26676672,AT5G66810,0.0,+,0.0
1387,Chr5,26795259,26795760,chipSampleRepAll_peak_1813,651.0,.,Chr5,26793879,26795369,AT5G67140,0.0,-,0.0
1388,Chr5,26822069,26822570,chipSampleRepAll_peak_1814,899.0,.,Chr5,26822431,26824328,AT5G67230,0.0,+,0.0
1391,Chr5,26853647,26854148,chipSampleRepAll_peak_1817,315.0,.,Chr5,26854021,26856006,AT5G67300,0.0,+,0.0
1392,Chr5,26874144,26874645,chipSampleRepAll_peak_1819,262.0,.,Chr5,26871890,26874850,AT5G67360,0.0,-,0.0
1393,Chr5,26879377,26879878,chipSampleRepAll_peak_1820,1771.0,.,Chr5,26877271,26879639,AT5G67370,0.0,-,0.0
1395,Chr5,26910421,26910922,chipSampleRepAll_peak_1822,156.0,.,Chr5,26910204,26912103,AT5G67430,0.0,+,0.0
1397,Chr5,26923340,26923841,chipSampleRepAll_peak_1824,105.0,.,Chr5,26921583,26923488,AT5G67460,0.0,-,0.0

In [81]:
# peaks names of peaks that overlap genes
closest_df.loc[closest_df.loc[:,"distance"]==0,"peak_name"]

0          chipSampleRepAll_peak_4
1          chipSampleRepAll_peak_6
2          chipSampleRepAll_peak_6
3          chipSampleRepAll_peak_8
4          chipSampleRepAll_peak_8
5         chipSampleRepAll_peak_10
6         chipSampleRepAll_peak_11
7         chipSampleRepAll_peak_13
9         chipSampleRepAll_peak_15
12        chipSampleRepAll_peak_18
14        chipSampleRepAll_peak_20
15        chipSampleRepAll_peak_21
16        chipSampleRepAll_peak_21
17        chipSampleRepAll_peak_22
18        chipSampleRepAll_peak_23
19        chipSampleRepAll_peak_24
20        chipSampleRepAll_peak_25
21        chipSampleRepAll_peak_27
22        chipSampleRepAll_peak_27
23        chipSampleRepAll_peak_28
27        chipSampleRepAll_peak_33
33        chipSampleRepAll_peak_45
34        chipSampleRepAll_peak_45
35        chipSampleRepAll_peak_47
36        chipSampleRepAll_peak_47
38        chipSampleRepAll_peak_49
39        chipSampleRepAll_peak_50
40        chipSampleRepAll_peak_51
41        chipSampleRepAll_peak_51
43       chipSampleRepAll_peak_53a
                   ...
1356    chipSampleRepAll_peak_1772
1358    chipSampleRepAll_peak_1775
1359    chipSampleRepAll_peak_1777
1360    chipSampleRepAll_peak_1778
1361    chipSampleRepAll_peak_1779
1362    chipSampleRepAll_peak_1779
1363    chipSampleRepAll_peak_1780
1364    chipSampleRepAll_peak_1781
1365    chipSampleRepAll_peak_1784
1366    chipSampleRepAll_peak_1785
1367    chipSampleRepAll_peak_1786
1369    chipSampleRepAll_peak_1789
1371    chipSampleRepAll_peak_1793
1372    chipSampleRepAll_peak_1793
1374    chipSampleRepAll_peak_1795
1375    chipSampleRepAll_peak_1797
1377    chipSampleRepAll_peak_1799
1378    chipSampleRepAll_peak_1800
1379    chipSampleRepAll_peak_1801
1380    chipSampleRepAll_peak_1802
1381    chipSampleRepAll_peak_1803
1384    chipSampleRepAll_peak_1807
1385    chipSampleRepAll_peak_1809
1387    chipSampleRepAll_peak_1813
1388    chipSampleRepAll_peak_1814
1391    chipSampleRepAll_peak_1817
1392    chipSampleRepAll_peak_1819
1393    chipSampleRepAll_peak_1820
1395    chipSampleRepAll_peak_1822
1397    chipSampleRepAll_peak_1824
Name: peak_name, Length: 996, dtype: object

In [82]:
test_df = closest_df.iloc[0:5]
closest_df.loc[(closest_df.loc[:,"distance"]==0) &
               (),"gene_name"]

,peak_chr,peak_start,peak_stop,peak_name,peak_signal,peak_strand,gene_chr,gene_start,gene_stop,gene_name,gene_signal,gene_strand,distance
0,Chr1,99170,99671,chipSampleRepAll_peak_4,449.0,.,Chr1,97411,99240,AT1G01230,0.0,+,0.0
1,Chr1,171294,171795,chipSampleRepAll_peak_6,171.0,.,Chr1,168558,171386,AT1G01460,0.0,+,0.0
2,Chr1,171294,171795,chipSampleRepAll_peak_6,171.0,.,Chr1,171524,172948,AT1G01470,0.0,-,0.0
3,Chr1,190092,190593,chipSampleRepAll_peak_8,436.0,.,Chr1,187144,190472,AT1G01510,0.0,+,0.0
4,Chr1,190092,190593,chipSampleRepAll_peak_8,436.0,.,Chr1,190407,192436,AT1G01520,0.0,+,0.0

In [89]:
test_df = closest_df.iloc[[1397,1396,1000,500],:]
test_df

,peak_chr,peak_start,peak_stop,peak_name,peak_signal,peak_strand,gene_chr,gene_start,gene_stop,gene_name,gene_signal,gene_strand,distance
1397,Chr5,26923340,26923841,chipSampleRepAll_peak_1824,105.0,.,Chr5,26921583,26923488,AT5G67460,0.0,-,0.0
1396,Chr5,26920686,26921187,chipSampleRepAll_peak_1823,628.0,.,Chr5,26921583,26923488,AT5G67460,0.0,-,397.0
1000,Chr4,13511129,13511630,chipSampleRepAll_peak_1297,101.0,.,Chr4,13511836,13513406,AT4G26890,0.0,+,-207.0
500,Chr2,15575648,15576149,chipSampleRepAll_peak_667,643.0,.,Chr2,15575995,15577916,AT2G37060,0.0,+,0.0

In [93]:
print(test_df.loc[(closest_df.loc[:,"distance"]>0) &
    (test_df.loc[:,"gene_chr"]=="Chr5"),
    "gene_name"])

1396    AT5G67460
Name: gene_name, dtype: object

In [94]:
test_df.to_csv("test.txt", sep="\t", header=True, index=False)

In [1]:
import pandas as pd 
peoples_df = pd.DataFrame({"name" : ["Bob", "Sue", "Tom", "Pam"],
                          "age" : [56, 21, 22, 35],
                          "inches" : [71, 63.5, 68.5, 62]})
peoples_df

   age  inches name
0   56    71.0  Bob
1   21    63.5  Sue
2   22    68.5  Tom
3   35    62.0  Pam

In [24]:
peoples_df.iloc[range(1,3),:]

   age  inches name
1   21    63.5  Sue
2   22    68.5  Tom

In [5]:
# set the row names to the "name" column
peoples_df = peoples_df.set_index("name")
peoples_df

      age  inches  centrimeters
name
Bob    56    71.0        180.34
Sue    21    63.5        161.29
Tom    22    68.5        173.99
Pam    35    62.0        157.48

In [28]:
peoples_df.loc[1,:]

TypeError: cannot do label indexing on <class 'pandas.core.indexes.base.Index'> with these indexers [1] of <type 'int'>

In [39]:
age_series= peoples_df.loc[:,"age"]
age_series

name
Bob    56
Sue    21
Tom    22
Pam    35
Name: age, dtype: int64

In [40]:
print 21 in age_series.values

True

In [41]:
print 100 in age_series.values

False

In [42]:
peoples_df.loc[peoples_df.loc[:,"age"]<50,:]

      age  inches
name
Sue    21    63.5
Tom    22    68.5
Pam    35    62.0

In [52]:
peoples_df.loc[(peoples_df.loc[:,"age"]<50) &
               (peoples_df.loc[:,"inches"]>65),:]

      age  inches
name
Tom    22    68.5

In [1]:
# Step 1
import pandas as pd # import pandas module
import numpy as np # import numpy module
                   # this module can classify
                    # python objects that make
                    # math easier later...

In [5]:
# Step 2
bedCols = ["chr", # chromosome location
             "start", # start location
             "stop", # stop location
             "name", # name of feature
             "score", # score of feature
             "strand"] # feature strand

In [6]:
# Step 3
bedCol_types = {"chr" : str,
                "start" : np.int64,
                "stop" : np.int64,
                "name" : str,
                "score" : np.float64,
                "strand":str}

In [9]:
# Step 4
bed_df = pd.read_table("example.bed",
                       sep = "\t", # out file is tab-delimited
                       header = None, # the column names are 
                                    # not in the file
                       names = bedCols, # sets column names
                       dtype = bedCol_types) # sets column types
bed_df # This show the top 3 lines of the dataframe

    chr  start   stop   name  score strand
0  Chr1   1100   1600  GeneA  255.0      +
1  Chr2  15230  15342  GeneB  255.0      -
2  Chr2  15352  15455  GeneC  255.0      +
3  Chr2  17006  18110  GeneD  255.0      +
4  Chr3  10704  11671  GeneE  255.0      -

In [10]:
closest_sorted_df.head()

NameError: name 'closest_sorted_df' is not defined

In [6]:
peoples_df.loc[:,"centrimeters"] = peoples_df.loc[:,"inches"] * 2.54
peoples_df

      age  inches  centrimeters
name
Bob    56    71.0        180.34
Sue    21    63.5        161.29
Tom    22    68.5        173.99
Pam    35    62.0        157.48

In [33]:
from decimal import Decimal
round(Decimal(2.550),1)

2.5

In [ ]:
import pandas as pd